server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mvassoler/ead-config-server-repo
          default-label: main
          username: marcosvassoler@yahoo.com.br
          password: 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

ead:
  configServer:
    username: configserver
    password: 'ead123cr'
  registerWithEureka:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.registerWithEureka.username}:${ead.registerWithEureka.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
