server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mvassoler/ead-config-server-repo
          default-label: main
          username: marcosvassoler@yahoo.com.br
          password: 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

ead:
  client:
    registerWithEureka:
      username: serviceregistry
      password: 'ead123sr'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.client.registerWithEureka.username}:${ead.client.registerWithEureka.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
