server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mvassoler/ead-config-server-repo
          default-label: main
          username: marcosvassoler@yahoo.com.br
          password: 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

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
